### ISSUE TITLE
Button on user profile for quick creation of private messages

### ISSUE THREAD

**Issue by jtojnar** [flagrow/byobu#28]
This could be either optional or even better, an another extension.

**Comment by bingvanmoorsel** [comment]
+1

**Comment by uamv** [comment]
This would be a great addition, especially now that the User Directory extension is available. I could see this being added to the menu available on a users profile … although, I don't recall if any menu is visible to non-admins.

**Comment by Luceos** [comment]
@uamv great point Joshua, will look into it.
