### ISSUE TITLE
Strip discussion-altering options

### ISSUE THREAD

**Issue by jordanjay29** [flagrow/byobu#3]
There's no need for private discussions to be affected by Askimet* (see #2 for flagging spam), Sticky, Lock, Split or other such altering options. 

*This is highly impractical considering mods/admins shouldn't have normal access to Private Discussions in order to monitor spam and remove false positives.

**Comment by Luceos** [comment]
I don't know for sure the extension should strip them by default ... Split might even come in handy or flag.

**Comment by jordanjay29** [comment]
Split might, but not lock or sticky.

**Comment by Luceos** [comment]
Why not sticky/lock a private discussion? I was actually thinking someone could use this extension to create private drafts or personal todos. Can't imagine the use cases when one can add groups as recipient.

**Comment by jordanjay29** [comment]
I'm having a hard time imagining use cases for lock, though. If someone wanted to leave the conversation, that seems like a good feature (something to look into, would they keep a copy of the conversation until then or lose access?), but locking seems over the top IMHO.

And I'd prefer a user-side Bookmark than Sticky which would have similar behavior but not globally. That's probably more of an extension request.

**Comment by Luceos** [comment]
I don't think I want to play too much of a role with other extensions. There might be good reasons to be able to lock. Who knows what group is allowed to lock, maybe it's only administrators or maybe it's the RPG game master who was attached to each Private Discussion by default.

Just .. reaching outside the box. It also seems to be a lot more difficult to remove logic of other extensions than I expected.. I'll guess that will deserve a post on the flarum/core tracker at some point too.

**Comment by jordanjay29** [comment]
Understood.

**Comment by jtojnar** [comment]
For private discussions, even tags are often unnecessary – category-less private discussions would be enough. Personal taxonomy may also prove to be more interesting than global tags, for this type of conversations.

**Comment by Luceos** [comment]
I've already considered removing the need for tags when a recipient was chosen. But influencing other extensions by default still seems like a very bad idea.

**Comment by issyrocks12** [comment]
You could put a PostPolicy in place, it checks for a private discussion and returns false on whatever you want to remove.

**Comment by Luceos** [comment]
@issyrocks12 although a good option, it's not a solution, it's a hack. You'd still see, for instance, the tag selection while creating a discussion. You'd see the flagging option etcetera.. (disregarding the fact we use flagging now too).

**Comment by Luceos** [comment]
I'm closing this one in favour of separate per-extension issues, starting with Split-support.
