### ISSUE TITLE
Private discussions area (filter)

### ISSUE THREAD

**Issue by GiacoR** [flagrow/byobu#32]
It would be great to have a way to filter for private discussions.
This could be a separate page at the user menu, header (links extension) or maybe somehow at the sidebar, like other tags.

Functionality should be like the other tags, you click on it and will be shown all private discussions you are part of.

**Comment by Luceos** [comment]
Try in search: `is:private`

Creating a separate page for private discussions is planned.

**Comment by luceos** [comment]
Closing this, no response.

**Comment by GiacoR** [comment]
Didn't expect you were waiting for a response... Searching for `is:private` works. Putting a static link to `/?q=is:private` works too but if you then click on a tag, you will be filtering for that tag **and** private discussions. Having a separate page would be a lot better.
