### ISSUE TITLE
Missing Byobu Decoration in Tag Views

### ISSUE THREAD

**Issue by pflstr** [flagrow/byobu#35]
As reported [here](https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/182) and [here](https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/193), private discussions in a tag view are missing / loosing the byobu badge and the recipients indicators after every reload. Reloading the *All Discussions* view however shows these discussions properly. After opening one of these discussions and returning to the tag view, this specific private discussion shows as intended... until the tag view page is reloaded again.

In the second post to which I linked above, I indicated that the situation might have improved somewhat with beta 7, but I'm not sure anymore. I think, prior to beta 7 I had the private discussions excluded from the *All Discussions* view via the hide setting of the tag used in my case. That's why I didn't notice the different behaviour in the *All Discussions* view compared to the tag view.

**Comment by luceos** [comment]
Let's try to reproduce this first.

**Comment by luceos** [comment]
Related to https://github.com/flarum/core/issues/1217

**Comment by luceos** [comment]
Fixed in master.
