### ISSUE TITLE
New private discussions via user profile exposed to public without any warning

### ISSUE THREAD

**Issue by pflstr** [flagrow/byobu#37]
Unfortunately Devflarum is down at the moment, so I cannot verify this issue there.

On two different installations I made the following observation: Whenever I create a new private discussion via the user profile and do not alter the recipients (leave it at the two preselected), the created discussion will be public, having the ``is_private`` field in the newly created entry in the ``discussions`` table set to 0, having the ``is_private`` field in the created ``posts`` entry set to 0, and missing the expected new entries in the ``recipients`` table.

The user posting this supposedly private discussion has no indicator or warning before submitting the post, that this will become public.

Once the preselected recipients are altered (even though I might return to the preselected set), the private discussion will be created as expected.

**Comment by luceos** [comment]
Wow I'll check this asap.
