### ISSUE TITLE
User list won't load (beta-7)

### ISSUE THREAD

**Issue by jrock17** [flagrow/byobu#38]
Using byobu 0.1.0-beta.18 and Flarum v0.1.0-beta.7.

When I open a new discussion window, the user list just spins and I can't continue. I have 410 members so not that many.

Thanks!

![2017-07-30_09-37-15](https://user-images.githubusercontent.com/1270524/28755230-f541eebc-750a-11e7-9321-5f3854e34882.png)

**Comment by luceos** [comment]
You have to type at least a few characters. In fact the placeholder says:

"Search recipient by typing first three characters..." not sure whether you missed that?

**Comment by jrock17** [comment]
Oh man, I see. Thanks.

I'd highly recommend removing the spinner and hiding the user list until someone types something. The way it's presented it looks like I need to wait for something that's loading and it made me think it was broken.

**Comment by luceos** [comment]
Okay that makes sense.
