### ISSUE TITLE
Cannot post a new public discussion, even after 0.1.0-beta.20

### ISSUE THREAD

**Issue by pascalpy** [flagrow/byobu#41]
Before the update, I was getting the same error. I ended up reinstalling the extension and it worked fine. After updating, I continue to obtain this error through inspect element on google chrome:

`Uncaught TypeError: Cannot read property 'toArray' forum-1f2c3c53.js:1090 of undefined`

Some info about my environment:
Ubuntu 16.10
Apache 2.4.18
PHP 7.0.18
Flarum 0.1.0-beta.7

For now I've disabled the extension, hopefully we can get this fixed!
If you need more info let me know!

**Comment by luceos** [comment]
Even after:

```
php flarum cache:clear
```

can you show the output of 

```
php flarum info
```

**Comment by pascalpy** [comment]
```
Flarum core 0.1.0-beta.7
PHP 7.0.18-0ubuntu0.16.10.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, yaml, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT clarkwinkelmann-comicsans v0.1.0
EXT datitisev-dashboard v0.1.0-beta.6
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea v0.1.1
EXT flarum-english v0.1.0-beta.7
EXT flagrow-upload 0.5.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT reflar-gamification 1.1.1
EXT reflar-user-management 0.1.4
EXT davis-socialprofile 0.2.3
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://theexperienceof.me/forum
Installation path: /var/www/html/forum
```

**Comment by luceos** [comment]
Ehm so does this work now?

**Comment by pascalpy** [comment]
Unfortunately, no.

**Comment by luceos** [comment]
I simply can't reproduce this. I just tried locally and on https://gravure.io/discuss, both run the latest version and both work. Can you tell me what piece of code is generating this error; it can be seen when clicking on the console error.

Thank you.

**Comment by pascalpy** [comment]
Interesting. It's working _now_. I'll report any other issues when they come up. Thanks for your time.
