### ISSUE TITLE
0.1.0-beta20 Can't post private discussion

### ISSUE THREAD

**Issue by jrock17** [flagrow/byobu#42]
I've updated to the latest and clear cache files. Regular posts work now but private discussions give "requested resource was not found". Debug:

`POST http://www.golfbuzz.com/api/discussions

{
  "errors": [
    {
      "status": "404",
      "code": "resource_not_found"
    }
  ]
}`

**Comment by luceos** [comment]
Did you set up the "view user list" permission for members?

**Comment by luceos** [comment]
https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/209

**Comment by luceos** [comment]
When creating a private discussion, the current user is no longer automatically added to it.
