### ISSUE TITLE
Request: make it possible for the Admin to see all and any Private Discussions

### ISSUE THREAD

**Issue by bikepost** [flagrow/byobu#43]
As a site owner/ operator, I don't need to sit and comb over all discussion but I need the tools to investigate an issue/ member, when reported by other or not, if the need arises.

We can disclose this in the Privacy Policies and User Agreement languages on the site or right when when a member creates a New Private Discussion ("Note: contents may be visible to Admin").

Thank you. 
I am new to GitHub. I see a Blue Enhancement tag but I don't know how to add it to this request.

**Comment by theportablegeek** [comment]
Definitely really REALLY support this!

**Comment by luceos** [comment]
Flagged discussions should become visible to users able to see flags.
