### ISSUE TITLE
Private discussions still become public after deactivating Byōbu

### ISSUE THREAD

**Issue by pflstr** [flagrow/byobu#50]
As far as I've understood, the purpose of the introduction of the `is-private` field into the `posts` and `discussions` tables was to avoid that private discussions become visible while Byōbu is deactivated e.g. during an upgrade process.

Right now however, Byōbu sets neither the `discussions.is-private` field nor the `posts.is-private` field beyond the original post to 1. The consequence is, that only private discussions without replies stay invisible after deactivating Byōbu, every private discussion with at least one reply becomes visible (bar the original post) to everyone (if not restricted otherwise).

This behaviour can be reproduced at the Devflarum sandbox server.

**Comment by luceos** [comment]
@pflstr just did a test locally and cannot reproduce. Did you first create a public discussion and make it private afterwards?

**Comment by pflstr** [comment]
I started the private discussions via the user profile link. Maybe, the issue only arises there. That's also the way I reproduced it at Devflarum.

**Comment by pflstr** [comment]
I think, this issue is related: https://github.com/flagrow/byobu/issues/37

The first post now gets the `posts.is-private` field set to 1 fixing the above issue, but the `discussions.is-private` field still doesn't, and maybe that's why replies don't get the `posts.is-private` set to 1 either.

**Comment by luceos** [comment]
Just tested this again:

![image](https://user-images.githubusercontent.com/504687/33004756-d7e109a0-cdc2-11e7-8941-6767e2d16043.png)
![image](https://user-images.githubusercontent.com/504687/33004763-dd225ed2-cdc2-11e7-816b-d8c9eda22e22.png)

Am I missing something @pflstr. If this is an issue I'd like to get all necessary information:

- Output of `php flarum:info`
- Steps to reproduce.

Thanks!

**Comment by pflstr** [comment]
- Login to DevFlarum as admin, enable Byobu.
- Grant the right to create private discussions to mods as well.
- Login as moduser5 and goto the admin profile https://devflarum.xyzz.work/u/admin
- Via controls-menu open a PD with the admin, choose any tag, don't change recipients.
- Login as admin again, reply in the PD.
- First bug: On the homepage and on the tag page, it still says:  moduser5 started ... minutes ago, there is no sign of my reply, the reply-count is still 0, even after page refresh.
- Disable Byobu.
- Second bug: Reload the start or tag page, the previously private discussion is still visible.
- Enter the previously private discussion, you see only the reply, the original post is hidden.
- Logout, you can still see the previously private discussion and inside just the reply.

`php flarum:info` is not at hand (DevFlarum).

**Comment by luceos** [comment]
Tagged 0.1.2 which addresses some private property things. Went over this full procedure to see whether I could reproduce again but to no avail. Would love to hear whether this is fixed for everyone.
