### ISSUE TITLE
Save as draft feature. Private discussion with your own self.

### ISSUE THREAD

**Issue by gurjyot** [flagrow/byobu#52]
I know it's kind of stupid, but the functionality is almost there. Instead of adding a recipient, you also give a button to make the discussion as a draft. In this the discussion is neither shared with any recipient or to the whole community instead, it just saves in a draft section. It's kind of a message to your own self. 

I hope this feature request makes sense for this extension.

**Comment by luceos** [comment]
I don't think this is something we will be adding. Byobu is about private discussions, not about draft discussions. If you can work with creating a PD with yourself to use as a draft, then please do.
